language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew build -x test

notifications:
  email:
    recipients: "-DenisViskov16@gmail.com"
    on_success: never # default: change
    on_failure: always # default: always
