language: java
jdk:
  - openjdk11
sudo: false

install: true

script: gradle build -x test

notifications:
  email:
    recipients: "-DenisViskov16@gmail.com"
    on_success: never # default: change
    on_failure: always # default: always
